myapps/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
	#主页
    url(r'^$', views.view,name='view'),

    #显示转派详情
    url(r'^/(?P<topic_id>\d+)/$',views.information,name='information'),

    #用于添加工单的网页
    url(r'^new_topic/$',views.new_topic,name='new_topic'),

    #用于修改工单的网页
    url(r'^edit_topic/(?P<topic_id>\d+)/$',views.edit_topic,name='edit_topic'),

    #用于转派工单
    url(r'^forward_topic/(?P<topic_id>\d+)/$',views.forward_topic,name='forward_topic'),

    #用于反馈
    url(r'^forward_topic1/(?P<topic_id>\d+)/$',views.forward_topic1,name='forward_topic1'),

    #用于删除
    url(r'^del_topic/(?P<topic_id>\d+)/$',views.del_topic,name='del_topic'),

    #用于完成
    url(r'^finished_topic/(?P<topic_id>\d+)/$',views.finished_topic,name='finished_topic'),

]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include('myapps.urls',namespace='myapps')),
]

myapps/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
	"""故障工单内容、申告时间、完成时间、申告人、完成人、状态（是否完成）"""
	text =  models.TextField()
	date_start = models.DateTimeField(auto_now_add=True)
	date_end = models.DateTimeField(null=True,blank=True)
	people_start = models.CharField(max_length=50)
	people_end = models.CharField(max_length=50,null=True,blank=True)
	state = models.CharField(max_length=10)

	def __str__(self):
		"""返回模型的字符串表示，前50个字符"""
		return self.text[:50]+"..."


class Distribute(models.Model):
	"""故障工单转派/反馈内容、时间、人"""
	topic = models.ForeignKey(Topic)
	text = models.TextField()
	dis_type = models.CharField(max_length=10) #转派还是反馈
	distribute_time = models.DateTimeField(auto_now_add=True)
	distribute_people = models.CharField(max_length=50)

	def __str__(self):
		return self.text[:50]+"..."

myapps/forms.py
from django import forms

from .models import Topic,Distribute

class TopicForm(forms.ModelForm):
	"""新增工单表单"""
	class Meta:
		model = Topic
		fields = ['text','people_start']
		labels = {'text':'内容','people_start':'申告人'}


class ForwardForm(forms.ModelForm):
	"""转派表单"""
	class Meta:
		model = Distribute
		fields = ['text','dis_type','distribute_people']
		labels = {'text':'备注','dis_type':'类型','distribute_people':'转派人'}


class ForwardForm1(forms.ModelForm):
	"""反馈表单"""
	class Meta:
		model = Distribute
		fields = ['text','distribute_people']
		labels = {'text':'备注','distribute_people':'反馈人'}

myapps/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from myapps.models import Topic,Distribute
from myapps.forms import TopicForm,ForwardForm,ForwardForm1

# Create your views here.

def view(request):
	"""显示工单的视频页"""
	limit = 5	#每页显示的记录数
	topics = Topic.objects.order_by('-date_start')	#按时间顺序取记录
	paginator = Paginator(topics,limit)	#实例化一个分页对象
	page =  request.GET.get('page')	#获取页码

	try:
		topics = paginator.page(page)	#获取页码对应的记录
	except PageNotAnInteger:	#如果页码不是整数
		topics = paginator.page(1)	#取第一页记录
	except EmptyPage:	#如果页码太大，没有相应的记录
		topics = paginator.page(paginator.num_pages)	#取最后一页的记录
	return render(request,'myapps/view.html',{'topics':topics})



def information(request,topic_id):
	"""显示相应工单及其详细转派内容"""
	topic = Topic.objects.get(id=topic_id)
	distributes = topic.distribute_set.order_by('-distribute_time')
	context = {'topic':topic,'distributes':distributes}
	return render(request,'myapps/information.html',context)


def new_topic(request):
	"""添加新工单"""
	if request.method != 'POST':
		form = TopicForm()
	else:
		form = TopicForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('myapps:view'))
	context = {'form':form}
	return render(request,'myapps/new_topic.html',context)


def edit_topic(request,topic_id):
	"""修改工单"""
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		form = TopicForm(instance=topic)
	else:
		form = TopicForm(instance=topic,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('myapps:view'))
	context = {'topic':topic,'form':form}
	return render(request,'myapps/edit_topic.html',context)


def forward_topic(request,topic_id):
	"""转派工单"""
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		form = ForwardForm()		
	else:	
		form = ForwardForm(data=request.POST)
		if form.is_valid():
			new_forward = form.save(commit=False)
			new_forward.topic = topic
			new_forward.save()
			return HttpResponseRedirect(reverse('myapps:view')) 
	context = {'topic':topic,'form':form}
	return render(request,'myapps/forward_topic.html',context)


def forward_topic1(request,topic_id):
	"""反馈信息"""
	topic = Topic.objects.get(id=topic_id)
	if request.method != 'POST':
		form = ForwardForm1()
	else:
		form = ForwardForm1(data=request.POST)
		if form.is_valid():
			new_forward = form.save(commit=False)
			new_forward.topic = topic
			new_forward.save()
			return HttpResponseRedirect(reverse('myapps:view')) 
	context = {'topic':topic,'form':form}
	return render(request,'myapps/forward_topic1.html',context)


def del_topic(request,topic_id):
	"""删除相应工单"""
	topic = Topic.objects.get(id=topic_id)
	if request.method == 'POST':
		topic.delete()
		return HttpResponseRedirect(reverse('myapps:view')) 
	context = {'topic':topic}
	return render(request,'myapps/del_topic.html',context)
	

def finished_topic(request,topic_id):
	"""完成工单"""
	topic = Topic.objects.get(id=topic_id)
	if request.method == 'POST':
		topic.update(state='完成')
	context = {'topic':topic}
	return render(request,'myapps/finished_topic.html',context)

myapps/templates/myapps/edit_topic.html
{% block content %}

<p>修改故障单：</p>
<form action="{% url 'myapps:edit_topic' topic.id %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">修改</button>
</form> 



{% endblock content %}

myapps/templates/myapps/forward_topic.html
{% block content %}

<p>转派：<select name="forwarder"></select></p>

<form action="{% url 'myapps:forward_topic' topic.id %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">确定</button>
</form> 



{% endblock content %}

myapps/templates/myapps/forward_topic1.html
{% block content %}

<p>反馈：</p>
<form action="{% url 'myapps:forward_topic1' topic.id %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">确定</button>
</form> 



{% endblock content %}

myapps/templates/myapps/information.html
{% block content %}

<p><a href="{% url 'myapps:view' %}">首页</a>>工单详情</p>
<p>{{ topic.text }}{{ topic.people_start }}

<ul>
<li>转派时间  转派人  转派备注</li>
{% for distr in distributes %}
  <li>
    <p>{{ distr.distribute_time|date:'M d,Y H:i' }}{{distr.distribute_people}}{{ distr.text|linebreaks }}</p>
  </li>
  {% empty %}
  <li>
  空
  </li>
{% endfor %}
</ul>

{% endblock content %}

myapps/templates/myapps/new_topic.html
{% block content %}



<p>新增故障单：</p>
<form action="{% url 'myapps:new_topic' %}" method='post'>
  {% csrf_token %}
  {{ form.as_p }}
  <button name="submit">添加</button>
</form> 



{% endblock content %}

myapps/templates/myapps/view.html
{% for topic in topics.object_list %}
  <li>{{topic.date_start|date:'M d, Y H:i'}}
      {{topic.text|linebreaks}}
      {{topic.people_start}}
      <a href="{% url 'myapps:information' topic.id %}">详情</a>
      <a href="{% url 'myapps:edit_topic' topic.id %}" >修改</a>
      <a href="{% url 'myapps:forward_topic' topic.id %}" target="_blank" >转派</a>
      <a href="{% url 'myapps:forward_topic1' topic.id %}" target="_blank" >反馈</a>
      <a href="#">删除</a>  
      <a href="#">完成</a>
  </li>

{% endfor %}

<p>
  {# topics.paginator.page_range 这个函数返回一个页码列表 #}
  {# 即 range(1,topics.paginator.num_pages + 1) #}

  {% for page_number in topics.paginator.page_range %}
    {% ifequal page_number topics.number %}
      {{ page_number }}
    {% else %}  
      <a href="?page={{ page_number }}">{{ page_number }}</a>
    {% endifequal %}
  {% endfor %}
</p>
<a href="{% url 'myapps:new_topic' %}">新增故障单</a>